version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    container_name: proxy
    ports:
      - "80:80"
      - "8080:8080"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik.yml:/traefik.yml

  nginx:
    image: nginx
    container_name: nginx
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.fernandok8s.com`)"
  
  apache:
    image: httpd
    container_name: apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`apache.fernandok8s.com`)"