entryPoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false

certificatesResolvers:
    mysolver:
        acme:
            email: fernando@codigofacilito.com
            storage: /acme.json
            httpChallenge:
                entryPoint: web